In [1]:
import pandas as pd

In [2]:
sales = pd.DataFrame({'Region':['E','E','W','W'],'Amount':[100,80,120,60]})

In [4]:
sales

  Region  Amount
0      E     100
1      E      80
2      W     120
3      W      60

In [ ]:
select Region,SUM(Amount) FROM sales group by Region

In [7]:
out = sales.groupby('Region').agg(total=('Amount','sum'),avg=('Amount','mean'))

In [8]:
out

        total   avg
Region
E         180  90.0
W         180  90.0

In [9]:
pd.pivot_table(sales,values='Amount',index='Region',columns = None,aggfunc='sum',fill_value = 0)

        Amount
Region
E          180
W          180

In [11]:
users = pd.DataFrame({'id':[1,2],'name':['Shalinee','Bindu']})
salary = pd.DataFrame({'id':[1,2,3],'salary':[10000,20000,40000]})

In [14]:
merged = users.merge(salary,on ='id',how='right')

In [15]:
merged

   id      name  salary
0   1  Shalinee   10000
1   2     Bindu   20000
2   3       NaN   40000

In [ ]:
select users.id,users.name ,salary.salary from users left join salary on users.id=salary.id

In [17]:
north = pd.DataFrame({'city':['NY'],'sales':[120]})
south = pd.DataFrame({'city':['LA'],'sales':[100]})

In [22]:
north

  city  sales
0   NY    120

In [23]:
south

  city  sales
0   LA    100

In [28]:
rows = pd.concat([north,south],axis=0,ignore_index=True)

In [29]:
rows

  city  sales
0   NY    120
1   LA    100

In [30]:
rows = pd.concat([north,south],axis=1,ignore_index=True)

In [32]:
rows

    0    1   2    3
0  NY  120  LA  100

In [33]:
rows = pd.concat([north[['city']],south[['city']]],axis=0,ignore_index=True)

In [34]:
rows

  city
0   NY
1   LA

In [35]:
cust = pd.Series(['alice','BOB','Charliee'])

In [36]:
clean_df= cust.str.strip().str.title()

In [37]:
clean_df

0       Alice
1         Bob
2    Charliee
dtype: object

In [39]:
mask=clean_df.str.contains('Bo',case=False)

In [40]:
mask

0    False
1     True
2    False
dtype: bool

In [41]:
cust = pd.Series(['alice','BOB','Charliee'])

In [48]:
mask=clean_df.str.contains('ice',case=True)

In [49]:
mask

0     True
1    False
2    False
dtype: bool

In [50]:
df = pd.DataFrame({"full_name":['Alice johnson','Bob smith','charliee Lee'],"age":[24,30,28]})

In [51]:
df['age_sq'] = df['age'].apply(lambda x:x*x)

In [52]:
df

       full_name  age  age_sq
0  Alice johnson   24     576
1      Bob smith   30     900
2   charliee Lee   28     784

In [53]:
df['full_name'] = df['full_name'].apply(lambda x: x.upper())

In [54]:
df

       full_name  age  age_sq
0  ALICE JOHNSON   24     576
1      BOB SMITH   30     900
2   CHARLIEE LEE   28     784

In [59]:
upper = df[["full_name"]].applymap(lambda x: x.upper())

C:\Users\prach\AppData\Local\Temp\ipykernel_15844\248877468.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  upper = df[["full_name"]].applymap(lambda x: x.upper())

In [56]:
df

       full_name  age  age_sq
0  ALICE JOHNSON   24     576
1      BOB SMITH   30     900
2   CHARLIEE LEE   28     784

In [60]:
upper

       full_name
0  ALICE JOHNSON
1      BOB SMITH
2   CHARLIEE LEE

In [61]:
df.rename(columns={"full_name": "FULL_NAME"}, inplace=True)

In [62]:
df

       FULL_NAME  age  age_sq
0  ALICE JOHNSON   24     576
1      BOB SMITH   30     900
2   CHARLIEE LEE   28     784

In [63]:
ts = pd.Series([10,20,30,40,50])

In [64]:
rolling_sum=ts.cumsum()

In [65]:
rolling_sum

0     10
1     30
2     60
3    100
4    150
dtype: int64

In [68]:
roll_avg = ts.rolling(2).mean()

In [69]:
roll_avg

0     NaN
1    15.0
2    25.0
3    35.0
4    45.0
dtype: float64

In [72]:
shift_test = ts.shift(2)

In [73]:
shift_test

0     NaN
1     NaN
2    10.0
3    20.0
4    30.0
dtype: float64

In [99]:
import pandas as pd

dates = pd.date_range("2025-01-01", periods=10, freq="D")
sales = [20,22,19,30,25,27,35,40,38,45]

In [100]:
df = pd.DataFrame({"date":dates,'sales':sales})

In [101]:
df

        date  sales
0 2025-01-01     20
1 2025-01-02     22
2 2025-01-03     19
3 2025-01-04     30
4 2025-01-05     25
5 2025-01-06     27
6 2025-01-07     35
7 2025-01-08     40
8 2025-01-09     38
9 2025-01-10     45

In [81]:
df['rolling_mean_3d'] = df['sales'].rolling(window=3).mean()

In [82]:
df

        date  sales  rolling_mean_3d
0 2025-01-01     20              NaN
1 2025-01-02     22              NaN
2 2025-01-03     19        20.333333
3 2025-01-04     30        23.666667
4 2025-01-05     25        24.666667
5 2025-01-06     27        27.333333
6 2025-01-07     35        29.000000
7 2025-01-08     40        34.000000
8 2025-01-09     38        37.666667
9 2025-01-10     45        41.000000

In [83]:
df['rolling_sum_3d'] = df['sales'].rolling(window=3).sum()

In [84]:
df

        date  sales  rolling_mean_3d  rolling_sum_3d
0 2025-01-01     20              NaN             NaN
1 2025-01-02     22              NaN             NaN
2 2025-01-03     19        20.333333            61.0
3 2025-01-04     30        23.666667            71.0
4 2025-01-05     25        24.666667            74.0
5 2025-01-06     27        27.333333            82.0
6 2025-01-07     35        29.000000            87.0
7 2025-01-08     40        34.000000           102.0
8 2025-01-09     38        37.666667           113.0
9 2025-01-10     45        41.000000           123.0

In [85]:
df['rolling_max_3d'] = df['sales'].rolling(window=3).max()

In [86]:
df

        date  sales  rolling_mean_3d  rolling_sum_3d  rolling_max_3d
0 2025-01-01     20              NaN             NaN             NaN
1 2025-01-02     22              NaN             NaN             NaN
2 2025-01-03     19        20.333333            61.0            22.0
3 2025-01-04     30        23.666667            71.0            30.0
4 2025-01-05     25        24.666667            74.0            30.0
5 2025-01-06     27        27.333333            82.0            30.0
6 2025-01-07     35        29.000000            87.0            35.0
7 2025-01-08     40        34.000000           102.0            40.0
8 2025-01-09     38        37.666667           113.0            40.0
9 2025-01-10     45        41.000000           123.0            45.0

In [88]:
df2 = pd.DataFrame({"store":["A"]*5 +["B"]*5,
                    "day":range(1,11),
                    "sales":[10,20,25,25,30,35,40,55,67,89]})

In [89]:
df2

  store  day  sales
0     A    1     10
1     A    2     20
2     A    3     25
3     A    4     25
4     A    5     30
5     B    6     35
6     B    7     40
7     B    8     55
8     B    9     67
9     B   10     89

In [91]:
df2['rolling_mean_perstore']=df2.groupby('store')['sales'].transform(lambda x:x.rolling(2).mean())

In [92]:
df2

  store  day  sales  rolling_mean_perstore
0     A    1     10                    NaN
1     A    2     20                   15.0
2     A    3     25                   22.5
3     A    4     25                   25.0
4     A    5     30                   27.5
5     B    6     35                    NaN
6     B    7     40                   37.5
7     B    8     55                   47.5
8     B    9     67                   61.0
9     B   10     89                   78.0

In [ ]:
Compute a 7-day rolling average of sales and compare with expanding average.

Find the rolling standard deviation (5 days) for a stock price dataset.

Use EWM to smooth noisy daily temperature data.

For each store, calculate the 3-day rolling sum of sales.

In [93]:
df

        date  sales  rolling_mean_3d  rolling_sum_3d  rolling_max_3d
0 2025-01-01     20              NaN             NaN             NaN
1 2025-01-02     22              NaN             NaN             NaN
2 2025-01-03     19        20.333333            61.0            22.0
3 2025-01-04     30        23.666667            71.0            30.0
4 2025-01-05     25        24.666667            74.0            30.0
5 2025-01-06     27        27.333333            82.0            30.0
6 2025-01-07     35        29.000000            87.0            35.0
7 2025-01-08     40        34.000000           102.0            40.0
8 2025-01-09     38        37.666667           113.0            40.0
9 2025-01-10     45        41.000000           123.0            45.0

In [94]:
df["expanding_mean"] = df["sales"].expanding().mean()

In [95]:
df

,date,sales,rolling_mean_3d,rolling_sum_3d,rolling_max_3d,expanding_mean
0,2025-01-01,20,NaN,NaN,NaN,20.000000
1,2025-01-02,22,NaN,NaN,NaN,21.000000
2,2025-01-03,19,20.333333,61.0,22.0,20.333333
3,2025-01-04,30,23.666667,71.0,30.0,22.750000
4,2025-01-05,25,24.666667,74.0,30.0,23.200000
5,2025-01-06,27,27.333333,82.0,30.0,23.833333
6,2025-01-07,35,29.000000,87.0,35.0,25.428571
7,2025-01-08,40,34.000000,102.0,40.0,27.250000
8,2025-01-09,38,37.666667,113.0,40.0,28.444444
9,2025-01-10,45,41.000000,123.0,45.0,30.100000

In [102]:
dates = pd.date_range("2025-01-01", periods=10, freq="MS")

In [103]:
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [104]:
dates = pd.date_range("2025-01-01", periods=10, freq="B")

In [105]:
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10',
               '2025-01-13', '2025-01-14'],
              dtype='datetime64[ns]', freq='B')

In [106]:
dates = pd.date_range("2025-01-01", periods=10, freq="W-MON")

In [107]:
dates

DatetimeIndex(['2025-01-06', '2025-01-13', '2025-01-20', '2025-01-27',
               '2025-02-03', '2025-02-10', '2025-02-17', '2025-02-24',
               '2025-03-03', '2025-03-10'],
              dtype='datetime64[ns]', freq='W-MON')

In [108]:
df = pd.DataFrame({'dates' : pd.date_range("2025-01-01", periods=10, freq="D")})

In [109]:
df

       dates
0 2025-01-01
1 2025-01-02
2 2025-01-03
3 2025-01-04
4 2025-01-05
5 2025-01-06
6 2025-01-07
7 2025-01-08
8 2025-01-09
9 2025-01-10

In [110]:
df["year"] = df["dates"].dt.year

In [111]:
df

       dates  year
0 2025-01-01  2025
1 2025-01-02  2025
2 2025-01-03  2025
3 2025-01-04  2025
4 2025-01-05  2025
5 2025-01-06  2025
6 2025-01-07  2025
7 2025-01-08  2025
8 2025-01-09  2025
9 2025-01-10  2025

In [112]:
df["month"] = df["dates"].dt.month

In [113]:
df

       dates  year  month
0 2025-01-01  2025      1
1 2025-01-02  2025      1
2 2025-01-03  2025      1
3 2025-01-04  2025      1
4 2025-01-05  2025      1
5 2025-01-06  2025      1
6 2025-01-07  2025      1
7 2025-01-08  2025      1
8 2025-01-09  2025      1
9 2025-01-10  2025      1

In [114]:
df["day"] = df["dates"].dt.day

In [115]:
df

       dates  year  month  day
0 2025-01-01  2025      1    1
1 2025-01-02  2025      1    2
2 2025-01-03  2025      1    3
3 2025-01-04  2025      1    4
4 2025-01-05  2025      1    5
5 2025-01-06  2025      1    6
6 2025-01-07  2025      1    7
7 2025-01-08  2025      1    8
8 2025-01-09  2025      1    9
9 2025-01-10  2025      1   10

In [116]:
df["weekday"] = df["dates"].dt.day_name()

In [117]:
df

       dates  year  month  day    weekday
0 2025-01-01  2025      1    1  Wednesday
1 2025-01-02  2025      1    2   Thursday
2 2025-01-03  2025      1    3     Friday
3 2025-01-04  2025      1    4   Saturday
4 2025-01-05  2025      1    5     Sunday
5 2025-01-06  2025      1    6     Monday
6 2025-01-07  2025      1    7    Tuesday
7 2025-01-08  2025      1    8  Wednesday
8 2025-01-09  2025      1    9   Thursday
9 2025-01-10  2025      1   10     Friday

In [120]:
df["week"] = df["dates"].dt.isocalendar().week

In [121]:
df

       dates  year  month  day    weekday  week
0 2025-01-01  2025      1    1  Wednesday     1
1 2025-01-02  2025      1    2   Thursday     1
2 2025-01-03  2025      1    3     Friday     1
3 2025-01-04  2025      1    4   Saturday     1
4 2025-01-05  2025      1    5     Sunday     1
5 2025-01-06  2025      1    6     Monday     2
6 2025-01-07  2025      1    7    Tuesday     2
7 2025-01-08  2025      1    8  Wednesday     2
8 2025-01-09  2025      1    9   Thursday     2
9 2025-01-10  2025      1   10     Friday     2

In [122]:
df["quarter"] = df["dates"].dt.quarter

In [123]:
df

       dates  year  month  day    weekday  week  quarter
0 2025-01-01  2025      1    1  Wednesday     1        1
1 2025-01-02  2025      1    2   Thursday     1        1
2 2025-01-03  2025      1    3     Friday     1        1
3 2025-01-04  2025      1    4   Saturday     1        1
4 2025-01-05  2025      1    5     Sunday     1        1
5 2025-01-06  2025      1    6     Monday     2        1
6 2025-01-07  2025      1    7    Tuesday     2        1
7 2025-01-08  2025      1    8  Wednesday     2        1
8 2025-01-09  2025      1    9   Thursday     2        1
9 2025-01-10  2025      1   10     Friday     2        1

In [124]:
from datetime import timedelta

In [125]:
df["date_plus_7"] = df["dates"] + pd.Timedelta(days=7)

In [126]:
df

       dates  year  month  day    weekday  week  quarter date_plus_7
0 2025-01-01  2025      1    1  Wednesday     1        1  2025-01-08
1 2025-01-02  2025      1    2   Thursday     1        1  2025-01-09
2 2025-01-03  2025      1    3     Friday     1        1  2025-01-10
3 2025-01-04  2025      1    4   Saturday     1        1  2025-01-11
4 2025-01-05  2025      1    5     Sunday     1        1  2025-01-12
5 2025-01-06  2025      1    6     Monday     2        1  2025-01-13
6 2025-01-07  2025      1    7    Tuesday     2        1  2025-01-14
7 2025-01-08  2025      1    8  Wednesday     2        1  2025-01-15
8 2025-01-09  2025      1    9   Thursday     2        1  2025-01-16
9 2025-01-10  2025      1   10     Friday     2        1  2025-01-17

In [129]:
df["date_plus_1M"] = df["dates"] + pd.DateOffset(months=1)

In [130]:
df

,dates,year,month,day,weekday,week,quarter,date_plus_7,date_plus_1M
0,2025-01-01,2025,1,1,Wednesday,1,1,2025-01-08,2025-02-01
1,2025-01-02,2025,1,2,Thursday,1,1,2025-01-09,2025-02-02
2,2025-01-03,2025,1,3,Friday,1,1,2025-01-10,2025-02-03
3,2025-01-04,2025,1,4,Saturday,1,1,2025-01-11,2025-02-04
4,2025-01-05,2025,1,5,Sunday,1,1,2025-01-12,2025-02-05
5,2025-01-06,2025,1,6,Monday,2,1,2025-01-13,2025-02-06
6,2025-01-07,2025,1,7,Tuesday,2,1,2025-01-14,2025-02-07
7,2025-01-08,2025,1,8,Wednesday,2,1,2025-01-15,2025-02-08
8,2025-01-09,2025,1,9,Thursday,2,1,2025-01-16,2025-02-09
9,2025-01-10,2025,1,10,Friday,2,1,2025-01-17,2025-02-10

In [131]:
df["date_plus_1Y"] = df["dates"] + pd.DateOffset(years=1)

In [132]:
df

,dates,year,month,day,weekday,week,quarter,date_plus_7,date_plus_1M,date_plus_1Y
0,2025-01-01,2025,1,1,Wednesday,1,1,2025-01-08,2025-02-01,2026-01-01
1,2025-01-02,2025,1,2,Thursday,1,1,2025-01-09,2025-02-02,2026-01-02
2,2025-01-03,2025,1,3,Friday,1,1,2025-01-10,2025-02-03,2026-01-03
3,2025-01-04,2025,1,4,Saturday,1,1,2025-01-11,2025-02-04,2026-01-04
4,2025-01-05,2025,1,5,Sunday,1,1,2025-01-12,2025-02-05,2026-01-05
5,2025-01-06,2025,1,6,Monday,2,1,2025-01-13,2025-02-06,2026-01-06
6,2025-01-07,2025,1,7,Tuesday,2,1,2025-01-14,2025-02-07,2026-01-07
7,2025-01-08,2025,1,8,Wednesday,2,1,2025-01-15,2025-02-08,2026-01-08
8,2025-01-09,2025,1,9,Thursday,2,1,2025-01-16,2025-02-09,2026-01-09
9,2025-01-10,2025,1,10,Friday,2,1,2025-01-17,2025-02-10,2026-01-10

In [ ]:
df["days_diff"] = (df["date